version: '3.4'

services:
  mydb:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'mydb'
      MYSQL_ROOT_PASSWORD: 'pp'
    ports:
      - 3306

  emp_system:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 2462
